[package]
name = "archive"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.90"
archive-sys = { path = "../archive-sys" }
log = "0.4.24"
thiserror = "1.0.64"

[dev-dependencies]
colog = "1.3.0"
